In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Trabalho Data Science 2 Bim/FIFA_data.csv',
                    sep=',', encoding='UTF-8')

In [ ]:
df.head()

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [ ]:
df = df.drop("Unnamed: 0", axis='columns')

In [ ]:
df.head()

ID               Name  Age  Overall                 Club    Value  \
0  158023           L. Messi   31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo   33       94             Juventus     €77M   
2  190871          Neymar Jr   26       92  Paris Saint-Germain  €118.5M   
3  193080             De Gea   27       91    Manchester United     €72M   
4  192985       K. De Bruyne   27       91      Manchester City    €102M   

    Wage Preferred Foot Height  Weight  
0  €565K           Left    5'7  159lbs  
1  €405K          Right    6'2  183lbs  
2  €290K          Right    5'9  150lbs  
3  €260K          Right    6'4  168lbs  
4  €355K          Right   5'11  154lbs

**ATRIBUTOS:** 

ID: id.

Age: idade.

Value: valor de mercado.

Wage: salário.

Overall: ranking dos melhores jogadores.

Club: clube.

Height: altura.

Weight: peso.

Preferred Foot: pé favorito.


**IDADE**

In [ ]:
import plotly.express as px

In [ ]:
hist =  px.histogram (df,  x = "idade", nbins=60) 
hist.update_layout(width=600,height=400,title_text='Distribuição idades jogadores') 
hist.show()

In [ ]:
hist =  px.histogram (df,  x = "pe favorito", nbins=60) 
hist.update_layout(width=600,height=400,title_text='Preferência de pé para jogar') 
hist.show()

In [ ]:
hist =  px.histogram (df,  x = "salario", nbins=60) 
hist.update_layout(width=1000,height=400,title_text='Distribuição salário jogadores') 
hist.show()

In [ ]:
hist =  px.histogram (df,  x = "valor", nbins=60) 
hist.update_layout(width=1000,height=400,title_text='Valor de mercado') 
hist.show()

In [ ]:
hist =  px.histogram (df,  x = "altura", nbins=60) 
hist.update_layout(width=1000,height=400,title_text='Altura') 
hist.show()

In [ ]:
hist =  px.histogram (df,  x = "peso", nbins=60) 
hist.update_layout(width=1000,height=400,title_text='Peso') 
hist.show()

In [ ]:
df.shape

(18206, 12)

## **TRATAMENTO DOS DADOS**

**Alterando nomes das colunas**

In [ ]:
df.head(2)

ID               Name  Age  Overall          Club    Value   Wage  \
0  158023           L. Messi   31       94  FC Barcelona  €110.5M  €565K   
1   20801  Cristiano Ronaldo   33       94      Juventus     €77M  €405K   

  Preferred Foot Height  Weight  
0           Left    5'7  159lbs  
1          Right    6'2  183lbs

In [ ]:
df.rename(columns={'ID': 'id'}, inplace=True)

In [ ]:
df.rename(columns={'Value': 'valor'}, inplace=True)
df.rename(columns={'Age': 'idade'}, inplace=True)
df.rename(columns={'Preferred Foot': 'pe favorito'}, inplace=True)
df.rename(columns={'Height': 'altura'}, inplace=True)
df.rename(columns={'Weight': 'peso'}, inplace=True)
df.rename(columns={'Name': 'nome'}, inplace=True)

In [ ]:
df.rename(columns={'Overall': 'ranking','Wage':'salario'}, inplace=True) 

In [ ]:
df.rename(columns={'Club': 'clube'}, inplace=True)

In [ ]:
df.head(3)

id               nome  idade  ranking                clube    valor  \
0  158023           L. Messi     31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo     33       94             Juventus     €77M   
2  190871          Neymar Jr     26       92  Paris Saint-Germain  €118.5M   

  salario Preferred Foot altura    peso  
0   €565K           Left    5'7  159lbs  
1   €405K          Right    6'2  183lbs  
2   €290K          Right    5'9  150lbs

**Valores Missing (NAN)**

In [ ]:
df.isnull().sum()

id                  0
nome                0
idade               0
ranking             0
clube             241
valor               0
salario             0
Preferred Foot     48
altura             48
peso               48
dtype: int64

In [ ]:
df[df.isna().any(axis=1)]

id            nome  idade  ranking clube valor salario  \
452    207439      L. Paredes     24       80   NaN   € 0     € 0   
538    156713    A. Granqvist     33       80   NaN   € 0     € 0   
568    229909        A. Lunev     26       79   NaN   € 0     € 0   
677    187347    I. Smolnikov     29       79   NaN   € 0     € 0   
874    187607       A. Dzyuba     29       78   NaN   € 0     € 0   
...       ...             ...    ...      ...   ...   ...     ...   
17197  245164        V. Kaith     21       55   NaN   € 0     € 0   
17215  243131        K. Taimi     26       55   NaN   € 0     € 0   
17339  233526        S. Passi     23       54   NaN   € 0     € 0   
17436  236452  D. Lalhlimpuia     20       54   NaN   € 0     € 0   
17539  234508        C. Singh     21       53   NaN   € 0     € 0   

      Preferred Foot altura    peso  
452            Right   5'11  165lbs  
538            Right    6'4  185lbs  
568            Right    6'2  176lbs  
677            Right   5'10  154lbs  
874            Right    6'5  201lbs  
...              ...    ...     ...  
17197          Right    6'2  176lbs  
17215          Right    6'4  187lbs  
17339          Right    5'9  143lbs  
17436          Right    6'0  168lbs  
17539          Right    6'3  174lbs  

[289 rows x 10 columns]

In [ ]:
df.dropna(inplace=True)

df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [id, nome, idade, ranking, clube, valor, salario, Preferred Foot, altura, peso]
Index: []

In [ ]:
df.head()

id               nome  idade  ranking                clube    valor  \
0  158023           L. Messi     31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo     33       94             Juventus     €77M   
2  190871          Neymar Jr     26       92  Paris Saint-Germain  €118.5M   
3  193080             De Gea     27       91    Manchester United     €72M   
4  192985       K. De Bruyne     27       91      Manchester City    €102M   

  salario Preferred Foot altura    peso  
0   €565K           Left    5'7  159lbs  
1   €405K          Right    6'2  183lbs  
2   €290K          Right    5'9  150lbs  
3   €260K          Right    6'4  168lbs  
4   €355K          Right   5'11  154lbs

In [ ]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [id, nome, idade, ranking, clube, valor, salario, Preferred Foot, altura, peso]
Index: []

In [ ]:
df.isnull().sum()

id                0
nome              0
idade             0
ranking           0
clube             0
valor             0
salario           0
Preferred Foot    0
altura            0
peso              0
dtype: int64

**Análise dos tipos de atributos.**

In [ ]:
df.dtypes

id                 int64
nome              object
idade              int64
ranking            int64
clube             object
valor             object
salario           object
Preferred Foot    object
altura            object
peso              object
dtype: object

**Dados Estatísticos**

In [ ]:
df.describe()

id         idade       ranking
count   17917.000000  17917.000000  17917.000000
mean   214223.925043     25.105765     66.237930
std     30042.427799      4.675007      6.927787
min        16.000000     16.000000     47.000000
25%    200235.000000     21.000000     62.000000
50%    221701.000000     25.000000     66.000000
75%    236508.000000     28.000000     71.000000
max    246620.000000     45.000000     94.000000

**Análise dos outliers**

In [ ]:
import plotly.express as px

In [ ]:
boxplot = px.box(df, y="idade")
boxplot.show()

In [ ]:
boxplot = px.box(df, y="salario")
boxplot.show()

In [ ]:
boxplot = px.box(df, y="clube")
boxplot.show()

In [ ]:
boxplot = px.box(df, y="altura")
boxplot.show()

In [ ]:
boxplot = px.box(df, y="peso")
boxplot.show()

## **PRÉ-PROCESSAMENTO**

In [ ]:
df.head(2)

id               nome  idade  ranking         clube    valor salario  \
0  158023           L. Messi     31       94  FC Barcelona  €110.5M   €565K   
1   20801  Cristiano Ronaldo     33       94      Juventus     €77M   €405K   

  pe favorito altura    peso  
0        Left    5'7  159lbs  
1       Right    6'2  183lbs

###**Excluir identificação do cliente**

In [ ]:
df2 = df.drop(labels = 'id', axis = 1)

In [ ]:
df2.head(2)

nome  idade  ranking         clube    valor salario  \
0           L. Messi     31       94  FC Barcelona  €110.5M   €565K   
1  Cristiano Ronaldo     33       94      Juventus     €77M   €405K   

  pe favorito altura    peso  
0        Left    5'7  159lbs  
1       Right    6'2  183lbs

###**Transformar variáveis categóricas em numéricas**

In [ ]:
df2['pe favorito'].replace({'Left': 0, 'Right': 1}, inplace=True)

In [ ]:
df2.head(3)

nome  idade  ranking                clube    valor salario  \
0           L. Messi     31       94         FC Barcelona  €110.5M   €565K   
1  Cristiano Ronaldo     33       94             Juventus     €77M   €405K   
2          Neymar Jr     26       92  Paris Saint-Germain  €118.5M   €290K   

   pe favorito altura    peso  
0            0    5'7  159lbs  
1            1    6'2  183lbs  
2            1    5'9  150lbs

In [ ]:
df['pe favorito'].replace({'Left': 0, 'Right': 1}, inplace=True)

###**Escalonamento**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
escala = StandardScaler()
df_esc = escala.fit_transform(df)

In [ ]:
df_esc

array([[-1.87077069,  1.26083209,  4.0074621 , -1.8179388 ],
       [-6.43850505,  1.68865086,  4.0074621 ,  0.55007352],
       [-0.77735318,  0.19128516,  3.71876157,  0.55007352],
       ...,
       [ 0.96336697, -1.30608054, -2.77700036,  0.55007352],
       [ 0.91253744, -1.9478087 , -2.77700036,  0.55007352],
       [ 1.06665711, -1.73389932, -2.77700036,  0.55007352]])

## **K-MEANS COM DOIS ATRIBUTOS**

In [ ]:
df2

id  idade  ranking                clube    valor salario  \
0      158023     31       94         FC Barcelona  €110.5M   €565K   
1       20801     33       94             Juventus     €77M   €405K   
2      190871     26       92  Paris Saint-Germain  €118.5M   €290K   
3      193080     27       91    Manchester United     €72M   €260K   
4      192985     27       91      Manchester City    €102M   €355K   
...       ...    ...      ...                  ...      ...     ...   
18201  243413     18       47         Waterford FC     €60K     €1K   
18202  238813     19       47      Crewe Alexandra     €60K     €1K   
18203  243165     19       47       Trelleborgs FF     €60K     €1K   
18204  241638     16       47     Cambridge United     €60K     €1K   
18205  246268     17       47      Tranmere Rovers     €60K     €1K   

      pe favorito altura    peso  
0            Left    5'7  159lbs  
1           Right    6'2  183lbs  
2           Right    5'9  150lbs  
3           Right    6'4  168lbs  
4           Right   5'11  154lbs  
...           ...    ...     ...  
18201        Left    6'1  168lbs  
18202       Right    5'9  134lbs  
18203       Right    6'3  170lbs  
18204       Right    5'8  148lbs  
18205       Right   5'10  154lbs  

[17917 rows x 9 columns]

In [ ]:
dados = df.iloc[:, [2,3]].values

In [ ]:
dados

array([[94,  0],
       [94,  1],
       [92,  1],
       ...,
       [47,  1],
       [47,  1],
       [47,  1]])

**Elbow Method**

In [ ]:
from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 5, max_iter = 300)
    kmeans.fit(dados)
   
    wcss.append(kmeans.inertia_)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
plt.figure(figsize=(10,5))
sns.lineplot(range(1, 11), wcss,marker='o',color='red')
plt.title('The Elbow Method')
plt.xlabel('Número de clusters')
plt.ylabel('WCSS');

**Agrupamento**

In [ ]:
kmeans = KMeans(n_clusters = 4, init = 'k-means++', random_state = 5, max_iter = 300)


In [ ]:
kmeans1 = kmeans.fit(dados)

In [ ]:
centroides = kmeans1.cluster_centers_
centroides

array([[63.37789883,  0.76077821],
       [77.26767677,  0.76107226],
       [55.61816916,  0.82074487],
       [69.62845327,  0.75268817]])

In [ ]:
classificacao = kmeans1.labels_
classificacao

array([1, 1, 1, ..., 2, 2, 2], dtype=int32)

In [ ]:
dados[3,:]

array([91,  1])

In [ ]:
classificacao[3]

1

In [ ]:
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
graf1 = px.scatter(x = dados[:,0], y = dados[:,1], color=classificacao)
graf2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [15, 15, 15, 15])
graf3 = go.Figure(data = graf1.data + graf2.data)
graf3.update_layout(width=800,height=500,title_text='Agrupamento K-Means')
graf3.update_xaxes(title = 'Salario')
graf3.update_yaxes(title = 'Valor')
graf3.show()

In [ ]:
agrupamento = pd.DataFrame(classificacao, columns = ['Grupo'])
agrupamento

Grupo
0          1
1          1
2          1
3          1
4          1
...      ...
17912      2
17913      2
17914      2
17915      2
17916      2

[17917 rows x 1 columns]

In [ ]:
df3 = pd.concat([df, agrupamento],axis=1)
df3

id  idade  ranking  pe favorito  Grupo
0      158023.0   31.0     94.0          0.0    1.0
1       20801.0   33.0     94.0          1.0    1.0
2      190871.0   26.0     92.0          1.0    1.0
3      193080.0   27.0     91.0          1.0    1.0
4      192985.0   27.0     91.0          1.0    1.0
...         ...    ...      ...          ...    ...
18201  243413.0   18.0     47.0          0.0    NaN
18202  238813.0   19.0     47.0          1.0    NaN
18203  243165.0   19.0     47.0          1.0    NaN
18204  241638.0   16.0     47.0          1.0    NaN
18205  246268.0   17.0     47.0          1.0    NaN

[18206 rows x 5 columns]

In [ ]:
df3.iloc[150 , :]

id             157481.0
idade              32.0
ranking            84.0
pe favorito         1.0
Grupo               1.0
Name: 150, dtype: float64

In [ ]:
df3.loc[df3.id == 92] 

Empty DataFrame
Columns: [id, idade, ranking, pe favorito, Grupo]
Index: []

In [ ]:
grupo0 = df3.loc[df3.Grupo == 0]
grupo0 

id  idade  ranking  pe favorito  Grupo
8619   216799.0   24.0     67.0          0.0    0.0
8620   220127.0   28.0     67.0          1.0    0.0
8621   234463.0   24.0     67.0          0.0    0.0
8622   244447.0   22.0     67.0          1.0    0.0
8623   221664.0   23.0     67.0          1.0    0.0
...         ...    ...      ...          ...    ...
15039  207513.0   26.0     60.0          1.0    0.0
15040  214425.0   27.0     60.0          1.0    0.0
15041  236697.0   23.0     60.0          1.0    0.0
15042  176793.0   30.0     60.0          1.0    0.0
15043  241051.0   20.0     60.0          1.0    0.0

[6425 rows x 5 columns]

In [ ]:
grupo0.shape

(6425, 5)

In [ ]:
grupo1 = df3.loc[df3.Grupo == 1]
grupo1

id  idade  ranking  pe favorito  Grupo
0     158023.0   31.0     94.0          0.0    1.0
1      20801.0   33.0     94.0          1.0    1.0
2     190871.0   26.0     92.0          1.0    1.0
3     193080.0   27.0     91.0          1.0    1.0
4     192985.0   27.0     91.0          1.0    1.0
...        ...    ...      ...          ...    ...
2569  212207.0   25.0     74.0          1.0    1.0
2570  225263.0   21.0     74.0          1.0    1.0
2571  186351.0   28.0     74.0          1.0    1.0
2572  163824.0   33.0     74.0          1.0    1.0
2573  203505.0   24.0     74.0          0.0    1.0

[2574 rows x 5 columns]

In [ ]:
grupo1.shape

(39, 6)

## **K Means com todos os atributos**

In [ ]:
df_esc

array([[-1.87077069,  1.26083209,  4.0074621 , -1.8179388 ],
       [-6.43850505,  1.68865086,  4.0074621 ,  0.55007352],
       [-0.77735318,  0.19128516,  3.71876157,  0.55007352],
       ...,
       [ 0.96336697, -1.30608054, -2.77700036,  0.55007352],
       [ 0.91253744, -1.9478087 , -2.77700036,  0.55007352],
       [ 1.06665711, -1.73389932, -2.77700036,  0.55007352]])

In [ ]:
df_esc.shape

(17917, 4)

**Elbow Method**

In [ ]:
from sklearn.cluster import KMeans
wcss = []
for i in range(1,15):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 5, max_iter = 300)
    kmeans.fit(df_esc)

    wcss.append(kmeans.inertia_)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
plt.figure(figsize=(10,5))
sns.lineplot(range(1, 15), wcss,marker='o',color='red')
plt.title('The Elbow Method')
plt.xlabel('Número de clusters')
plt.ylabel('WCSS');

**Agrupamento**

In [ ]:
kmeans = KMeans(n_clusters = 6, init = 'k-means++', random_state = 5, max_iter = 300)


In [ ]:
kmeans2 = kmeans.fit(df_esc)

In [ ]:
centroides = kmeans2.cluster_centers_
centroides

array([[-0.99692792,  1.20410305,  0.61669374,  0.55007352],
       [ 0.76014944, -0.96821736, -1.05717842,  0.55007352],
       [ 0.62181041, -0.72124427, -0.48007788, -1.8179388 ],
       [ 0.17389959, -0.05266192,  0.37764104,  0.55007352],
       [-0.50669224,  0.67503002,  0.6450462 , -1.8179388 ],
       [-5.02249268,  2.27048439,  0.43719888,  0.04489756]])

In [ ]:
escala.inverse_transform(kmeans2.cluster_centers_)

array([[1.84274626e+05, 3.07347987e+01, 7.05101342e+01, 1.00000000e+00],
       [2.37060023e+05, 2.05794687e+01, 5.89142278e+01, 1.00000000e+00],
       [2.32904098e+05, 2.17340374e+01, 6.29121459e+01, 7.77156117e-16],
       [2.19448145e+05, 2.48595775e+01, 6.88540742e+01, 1.00000000e+00],
       [1.99002085e+05, 2.82614476e+01, 7.07065485e+01, 7.77156117e-16],
       [6.33402622e+04, 3.57200000e+01, 6.92666667e+01, 7.86666667e-01]])

In [ ]:
classificacao2 = kmeans2.labels_
classificacao2

array([4, 5, 0, ..., 1, 1, 1], dtype=int32)

In [ ]:
classificacao2[199]

0

In [ ]:
agrupamento2 = pd.DataFrame(classificacao2, columns = ['Grupo'])
agrupamento2

Grupo
0          4
1          5
2          0
3          0
4          0
...      ...
17912      2
17913      1
17914      1
17915      1
17916      1

[17917 rows x 1 columns]

In [ ]:
df4 = pd.concat([df, agrupamento2],axis=1)
df4

id  idade  ranking  pe favorito  Grupo
0      158023.0   31.0     94.0          0.0    4.0
1       20801.0   33.0     94.0          1.0    5.0
2      190871.0   26.0     92.0          1.0    0.0
3      193080.0   27.0     91.0          1.0    0.0
4      192985.0   27.0     91.0          1.0    0.0
...         ...    ...      ...          ...    ...
18201  243413.0   18.0     47.0          0.0    NaN
18202  238813.0   19.0     47.0          1.0    NaN
18203  243165.0   19.0     47.0          1.0    NaN
18204  241638.0   16.0     47.0          1.0    NaN
18205  246268.0   17.0     47.0          1.0    NaN

[18206 rows x 5 columns]

In [ ]:
df4.iloc[125 , :]

id             200104.0
idade              25.0
ranking            84.0
pe favorito         1.0
Grupo               3.0
Name: 125, dtype: float64

In [ ]:
df4.loc[df4.id == 76] 

Empty DataFrame
Columns: [id, idade, ranking, pe favorito, Grupo]
Index: []

In [ ]:
grupo0 = df4.loc[df4.Grupo == 0]
grupo0 

id  idade  ranking  pe favorito  Grupo
2      190871.0   26.0     92.0          1.0    0.0
3      193080.0   27.0     91.0          1.0    0.0
4      192985.0   27.0     91.0          1.0    0.0
5      183277.0   27.0     91.0          1.0    0.0
6      177003.0   32.0     91.0          1.0    0.0
...         ...    ...      ...          ...    ...
16841  242567.0   22.0     56.0          1.0    0.0
16924  239548.0   18.0     56.0          1.0    0.0
17045  242462.0   18.0     55.0          0.0    0.0
17383  241519.0   25.0     54.0          1.0    0.0
17553  238373.0   19.0     53.0          1.0    0.0

[3516 rows x 5 columns]

In [ ]:
grupo0.shape

(3516, 5)