In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Trabalho Data Science 2 Bim/FIFA_data-limpo.csv',
                    sep=',', encoding='UTF-8')

In [6]:
df.head()

ID               Name  Age  Overall                 Club    Value  \
0  158023           L. Messi   31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo   33       94             Juventus     €77M   
2  190871          Neymar Jr   26       92  Paris Saint-Germain  €118.5M   
3  193080             De Gea   27       91    Manchester United     €72M   
4  192985       K. De Bruyne   27       91      Manchester City    €102M   

    Wage Preferred Foot Height  Weight  
0  €565K           Left    5'7  159lbs  
1  €405K          Right    6'2  183lbs  
2  €290K          Right    5'9  150lbs  
3  €260K          Right    6'4  168lbs  
4  €355K          Right   5'11  154lbs

**ATRIBUTOS:** 

ID: id jogador.

Age: idade.

Overall	:	Ranking geral.

Club: clube.

Valor: value.

Wage: salário.

Preferred Foot: pe favorito.

Height: altura.

Weight: peso.

## **Tratamento de Dados**

**Alterando nomes das colunas**

In [7]:
df.head(2)

ID               Name  Age  Overall          Club    Value   Wage  \
0  158023           L. Messi   31       94  FC Barcelona  €110.5M  €565K   
1   20801  Cristiano Ronaldo   33       94      Juventus     €77M  €405K   

  Preferred Foot Height  Weight  
0           Left    5'7  159lbs  
1          Right    6'2  183lbs

In [8]:
df.rename(columns={'ID': 'identificacao jogador'}, inplace=True)

In [9]:
df.rename(columns={'Name': 'nome'}, inplace=True)
df.rename(columns={'Age': 'idade'}, inplace=True)
df.rename(columns={'Club': 'clube'}, inplace=True)
df.rename(columns={'Value': 'valor'}, inplace=True)
df.rename(columns={'Wage': 'salario'}, inplace=True)
df.rename(columns={'Height': 'altura'}, inplace=True)
df.rename(columns={'Weight': 'peso'}, inplace=True)
df.rename(columns={'Overall': 'ranking'}, inplace=True)
df.rename(columns={'Preferred Foot': 'pe favorito'}, inplace=True)

In [10]:
df.rename(columns={'ranking geral': 'ranking'}, inplace=True)

In [12]:
df.rename(columns={'identificacao jogador': 'id'}, inplace=True)

In [13]:
df.head(3)

id               nome  idade  ranking                clube    valor  \
0  158023           L. Messi     31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo     33       94             Juventus     €77M   
2  190871          Neymar Jr     26       92  Paris Saint-Germain  €118.5M   

  salario pe favorito altura    peso  
0   €565K        Left    5'7  159lbs  
1   €405K       Right    6'2  183lbs  
2   €290K       Right    5'9  150lbs

**Valores Missing (NAN)**

In [14]:
df.isnull().sum()

id             0
nome           0
idade          0
ranking        0
clube          0
valor          0
salario        0
pe favorito    0
altura         0
peso           0
dtype: int64

**Análise dos tipos de atributos.**

In [15]:
df.dtypes

id              int64
nome           object
idade           int64
ranking         int64
clube          object
valor          object
salario        object
pe favorito    object
altura         object
peso           object
dtype: object

**Dados Estatísticos**

In [16]:
df.describe()

id         idade       ranking
count   17917.000000  17917.000000  17917.000000
mean   214223.925043     25.105765     66.237930
std     30042.427799      4.675007      6.927787
min        16.000000     16.000000     47.000000
25%    200235.000000     21.000000     62.000000
50%    221701.000000     25.000000     66.000000
75%    236508.000000     28.000000     71.000000
max    246620.000000     45.000000     94.000000

**Análise dos outliers**

In [17]:
import plotly.express as px

In [18]:
boxplot = px.box(df, y="idade")
boxplot.show()

In [19]:
boxplot = px.box(df, y="altura")
boxplot.show()

In [20]:
boxplot = px.box(df, y="peso")
boxplot.show()

In [21]:
boxplot = px.box(df, y="clube")
boxplot.show()

## **Pré-Processamento**

In [22]:
df.head(2)

id               nome  idade  ranking         clube    valor salario  \
0  158023           L. Messi     31       94  FC Barcelona  €110.5M   €565K   
1   20801  Cristiano Ronaldo     33       94      Juventus     €77M   €405K   

  pe favorito altura    peso  
0        Left    5'7  159lbs  
1       Right    6'2  183lbs

###**Excluir identificação do cliente**

In [23]:
df2 = df.drop(labels = 'id', axis = 1)

In [24]:
df2.head(2)

nome  idade  ranking         clube    valor salario  \
0           L. Messi     31       94  FC Barcelona  €110.5M   €565K   
1  Cristiano Ronaldo     33       94      Juventus     €77M   €405K   

  pe favorito altura    peso  
0        Left    5'7  159lbs  
1       Right    6'2  183lbs

###**Transformar variáveis categóricas em numéricas**

In [25]:
df2['pe favorito'].replace({'Left': 0, 'Right': 1}, inplace=True)

In [52]:
df2.head(3)

id               nome  idade  ranking    valor salario pe favorito  \
0  158023           L. Messi     31       94  €110.5M   €565K        Left   
1   20801  Cristiano Ronaldo     33       94     €77M   €405K       Right   
2  190871          Neymar Jr     26       92  €118.5M   €290K       Right   

  altura    peso  
0    5'7  159lbs  
1    6'2  183lbs  
2    5'9  150lbs

In [42]:
df['pe favorito'].replace({'Left': 0, 'Right': 1}, inplace=True)

###**Escalonamento**

In [27]:
from sklearn.preprocessing import StandardScaler

In [49]:
escala = StandardScaler()
df_esc = escala.fit_transform(df)

In [56]:
df_esc

array([[-1.87077069,  1.26083209,  4.0074621 , -1.8179388 ],
       [-6.43850505,  1.68865086,  4.0074621 ,  0.55007352],
       [-0.77735318,  0.19128516,  3.71876157,  0.55007352],
       ...,
       [ 0.96336697, -1.30608054, -2.77700036,  0.55007352],
       [ 0.91253744, -1.9478087 , -2.77700036,  0.55007352],
       [ 1.06665711, -1.73389932, -2.77700036,  0.55007352]])

## **Agrupamento Hierárquico**


In [58]:
df_esc

array([[-1.87077069,  1.26083209,  4.0074621 , -1.8179388 ],
       [-6.43850505,  1.68865086,  4.0074621 ,  0.55007352],
       [-0.77735318,  0.19128516,  3.71876157,  0.55007352],
       ...,
       [ 0.96336697, -1.30608054, -2.77700036,  0.55007352],
       [ 0.91253744, -1.9478087 , -2.77700036,  0.55007352],
       [ 1.06665711, -1.73389932, -2.77700036,  0.55007352]])

In [59]:
df_esc.shape

(17917, 4)

**Dendograma**

In [62]:
from sklearn.cluster import AgglomerativeClustering

In [63]:
hier = AgglomerativeClustering(n_clusters=7, affinity='euclidean', linkage = 'average')
classificacao = hier.fit_predict(df_esc)

In [64]:
classificacao

array([5, 0, 1, ..., 1, 1, 1])

A visualização fica interessante quando tempos de dois a tres dimensões. Neste caso estamos trabalhando com 4 dimensões. 


**Agrupamento**

In [65]:
agrupamento = pd.DataFrame(classificacao, columns = ['ranking geral'])
agrupamento

ranking geral
0                  5
1                  0
2                  1
3                  1
4                  1
...              ...
17912              2
17913              1
17914              1
17915              1
17916              1

[17917 rows x 1 columns]

In [66]:
df_hc = pd.concat([df, agrupamento],axis=1)
df_hc

id  idade  ranking  pe favorito  ranking geral
0      158023     31       94            0              5
1       20801     33       94            1              0
2      190871     26       92            1              1
3      193080     27       91            1              1
4      192985     27       91            1              1
...       ...    ...      ...          ...            ...
17912  243413     18       47            0              2
17913  238813     19       47            1              1
17914  243165     19       47            1              1
17915  241638     16       47            1              1
17916  246268     17       47            1              1

[17917 rows x 5 columns]

In [68]:
df_hc.loc[df.id == 158023]

id  idade  ranking  pe favorito  ranking geral
0  158023     31       94            0              5

In [77]:
geral = df_hc.loc[df_hc.ranking == 90]
geral.head(2)

id  idade  ranking  pe favorito  ranking geral
9   200389     25       90            1              1
10  188545     29       90            1              1