In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv('/content/drive/MyDrive/Trabalho Data Science 2 Bim/FIFA_data-limpo.csv',
                    sep=',', encoding='UTF-8')

In [5]:
df.head()

ID               Name  Age  Overall                 Club    Value  \
0  158023           L. Messi   31       94         FC Barcelona  €110.5M   
1   20801  Cristiano Ronaldo   33       94             Juventus     €77M   
2  190871          Neymar Jr   26       92  Paris Saint-Germain  €118.5M   
3  193080             De Gea   27       91    Manchester United     €72M   
4  192985       K. De Bruyne   27       91      Manchester City    €102M   

    Wage Preferred Foot Height  Weight  
0  €565K           Left    5'7  159lbs  
1  €405K          Right    6'2  183lbs  
2  €290K          Right    5'9  150lbs  
3  €260K          Right    6'4  168lbs  
4  €355K          Right   5'11  154lbs

**ATRIBUTOS:** 

ID: id jogador.

Age: idade.

Overall	:	Ranking geral.

Club: clube.

Valor: value.

Wage: salário.

Preferred Foot: pe favorito.

Height: altura.

Weight: peso.

### **Transformação de variáveis categóricas em numéricas**

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
df.head()

ID               Name  Age  Overall                 Club  Value   Wage  \
0  158023           L. Messi   31       94         FC Barcelona   9465  €565K   
1   20801  Cristiano Ronaldo   33       94             Juventus   3090  €405K   
2  190871          Neymar Jr   26       92  Paris Saint-Germain  12304  €290K   
3  193080             De Gea   27       91    Manchester United   4059  €260K   
4  192985       K. De Bruyne   27       91      Manchester City   8471  €355K   

  Preferred Foot Height  Weight  Genre  
0           Left    5'7  159lbs   9465  
1          Right    6'2  183lbs   3090  
2          Right    5'9  150lbs  12304  
3          Right    6'4  168lbs   4059  
4          Right   5'11  154lbs   8471

In [19]:
df_pca = df.iloc[:,:].values
df_pca

array([[158023, 'L. Messi', 31, ..., "5'7", '159lbs', 9465],
       [20801, 'Cristiano Ronaldo', 33, ..., "6'2", '183lbs', 3090],
       [190871, 'Neymar Jr', 26, ..., "5'9", '150lbs', 12304],
       ...,
       [243165, 'N. Christoffersson', 19, ..., "6'3", '170lbs', 11900],
       [241638, 'B. Worman', 16, ..., "5'8", '148lbs', 2083],
       [246268, 'D. Walker-Rice', 17, ..., "5'10", '154lbs', 3921]],
      dtype=object)

In [20]:
le = LabelEncoder()
df_pca = le.fit_transform(df_pca[:,1])
df_pca

array([ 9465,  3090, 12304, ..., 11900,  2083,  3921])

In [21]:
list(le.classes_)

['A. Abang',
 'A. Abdellaoui',
 'A. Abdennour',
 'A. Abdi',
 'A. Abdu Jaber',
 'A. Abdulhameed',
 'A. Abedzadeh',
 'A. Abeid',
 'A. Ablet',
 'A. Abrashi',
 'A. Absalem',
 'A. Accardi',
 'A. Acevedo',
 'A. Acosta',
 'A. Acquah',
 'A. Adam',
 'A. Addai',
 'A. Ademi',
 'A. Ademoglu',
 'A. Adetula',
 'A. Adnan',
 'A. Adomah',
 'A. Adouyev',
 'A. Affane',
 'A. Agouda',
 'A. Aguerre',
 'A. Aguilar',
 'A. Ahl Holmström',
 'A. Ahmed',
 'A. Ajagun',
 'A. Ajdarević',
 'A. Ajeti',
 'A. Akinfenwa',
 'A. Akinola',
 'A. Akinyemi',
 'A. Akkaynak',
 'A. Aktas',
 'A. Al Ammar',
 'A. Al Amri',
 'A. Al Arishi',
 'A. Al Arraf',
 'A. Al Aryani',
 'A. Al Asmari',
 'A. Al Bahri',
 'A. Al Barakah',
 'A. Al Basisi',
 'A. Al Bishi',
 'A. Al Bulayhi',
 'A. Al Dakheel',
 'A. Al Dawsari',
 'A. Al Dhafeeri',
 'A. Al Dohaim',
 'A. Al Enazi',
 'A. Al Fahad',
 'A. Al Faraj',
 'A. Al Fiqi',
 'A. Al Fraidi',
 'A. Al Ghamdi',
 'A. Al Habib',
 'A. Al Habsi',
 'A. Al Hafith',
 'A. Al Hamdan',
 'A. Al Harbi',
 'A. Al Hassan

In [22]:
df['Value'] = df_pca
df.head()

ID               Name  Age  Overall                 Club  Value   Wage  \
0  158023           L. Messi   31       94         FC Barcelona   9465  €565K   
1   20801  Cristiano Ronaldo   33       94             Juventus   3090  €405K   
2  190871          Neymar Jr   26       92  Paris Saint-Germain  12304  €290K   
3  193080             De Gea   27       91    Manchester United   4059  €260K   
4  192985       K. De Bruyne   27       91      Manchester City   8471  €355K   

  Preferred Foot Height  Weight  Genre  
0           Left    5'7  159lbs   9465  
1          Right    6'2  183lbs   3090  
2          Right    5'9  150lbs  12304  
3          Right    6'4  168lbs   4059  
4          Right   5'11  154lbs   8471

In [23]:
inverted = le.inverse_transform(df_pca)
print(inverted)

['L. Messi' 'Cristiano Ronaldo' 'Neymar Jr' ... 'N. Christoffersson'
 'B. Worman' 'D. Walker-Rice']


### PCA

**Extração de Características:** Encontra os relacionamentos dos melhores atributos e cria novos atributos.

É um algoritmo de aprendizagem não supervisionada.

Aplica-se em dados linearmente separáveis.

In [27]:
from sklearn.decomposition import PCA

In [28]:
pca = PCA(n_components=2)

In [42]:
df = df.drop(labels = 'Weight', axis = 1)

In [38]:
df['Preferred Foot'].replace({'Left': 0, 'Right': 1}, inplace=True)

In [43]:
pca_transform = pca.fit_transform(df)

In [44]:
pca_transform.shape

(17917, 2)

In [45]:
pca_transform

array([[ 56200.11417877,   1501.60136392],
       [193427.02761441,  -7438.89105198],
       [ 23349.92084329,   5498.57145064],
       ...,
       [-28943.76310868,   4898.6025519 ],
       [-27409.16370671,  -8983.89403895],
       [-32040.58576384,  -6387.10443003]])

In [46]:
pca.explained_variance_ratio_

array([0.95012944, 0.04987051])

In [48]:
pca.explained_variance_ratio_.sum()

0.9999999477002967

In [49]:
import plotly.express as px

In [53]:
labels = {
    str(i): f"PC {i+1} ({var:.1f}%)"
    for i, var in enumerate(pca.explained_variance_ratio_ * 100)
}

fig = px.scatter_matrix(
    pca_transform,
    labels=labels,
    dimensions=range(2), 
    color=df["Value"]
)
fig.update_traces(diagonal_visible=False)
fig.show()